[target.'cfg(target_arch = "x86_64")']
rustflags = ["-C", "target-cpu=native"]

[target.'cfg(target_arch = "aarch64")']
rustflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]
